"""The migration must build exactly what the models describe, and it must be reversible.

`alembic check` is the real assertion here: it fails if the models and the migration have drifted,
which is the failure mode that only shows up in production otherwise.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from core.models import Base

API_DIR = Path(__file__).resolve().parents[1]


def test_upgrade_creates_every_table(migrated: str):
    engine = sa.create_engine(migrated)
    try:
        tables = set(sa.inspect(engine).get_table_names())
    finally:
        engine.dispose()
    assert set(Base.metadata.tables) <= tables
    assert "alembic_version" in tables


def test_alembic_check_reports_no_drift(migrated: str, alembic_config):
    """If this fails, the models changed and the migration did not."""
    try:
        command.check(alembic_config(migrated))
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"models and migration have drifted: {exc}")


def test_the_generated_column_and_the_partial_index_survived_autogenerate(migrated: str):
    """Autogenerate does not always emit Computed columns or postgresql_where. Both carry product
    rules, so they are asserted against the live database rather than against the model."""
    engine = sa.create_engine(migrated)
    try:
        with engine.connect() as conn:
            generated = conn.execute(
                sa.text(
                    "select is_generated, generation_expression from information_schema.columns"
                    " where table_name = 'org_datum' and column_name = 'is_gap'"
                )
            ).one()
            index = conn.execute(
                sa.text("select indexdef from pg_indexes where indexname = 'uq_org_datum_current'")
            ).scalar_one()
    finally:
        engine.dispose()
    assert generated.is_generated == "ALWAYS"
    assert "IS NULL" in generated.generation_expression
    assert "WHERE (superseded_at IS NULL)" in index
    assert "UNIQUE INDEX" in index


def test_the_provenance_check_exists_in_the_migrated_database(migrated: str):
    engine = sa.create_engine(migrated)
    try:
        with engine.connect() as conn:
            names = set(
                conn.execute(
                    sa.text(
                        "select conname from pg_constraint c"
                        " join pg_class t on t.oid = c.conrelid"
                        " where t.relname = 'org_datum' and c.contype = 'c'"
                    )
                ).scalars()
            )
    finally:
        engine.dispose()
    assert "ck_org_datum_provenance" in names
    assert "ck_org_datum_gap_reason" in names


def test_downgrade_and_upgrade_again_is_clean(scratch_db_url: str, migrated: str, alembic_config):
    config = alembic_config(scratch_db_url)
    command.downgrade(config, "base")
    engine = sa.create_engine(scratch_db_url)
    try:
        remaining = set(sa.inspect(engine).get_table_names()) - {"alembic_version"}
    finally:
        engine.dispose()
    assert remaining == set(), f"downgrade left tables behind: {sorted(remaining)}"
    command.upgrade(config, "head")
