"use client";

// Generated by `npx shadcn@4.19.0 add popover`, then adapted to this project's rules:
// no shadow, no border radius, and no enter/exit animation beyond a 120 ms opacity fade.
// The utilities shadcn shipped with (shadow-md, rounded-lg, animate-in, zoom-in-95) do
// not exist here, because globals.css deletes the radius and shadow namespaces outright.
import * as React from "react";
import { Popover as PopoverPrimitive } from "radix-ui";

import { cn } from "@/lib/utils";

function Popover({ ...props }: React.ComponentProps<typeof PopoverPrimitive.Root>) {
  return <PopoverPrimitive.Root data-slot="popover" {...props} />;
}

function PopoverTrigger({ ...props }: React.ComponentProps<typeof PopoverPrimitive.Trigger>) {
  return <PopoverPrimitive.Trigger data-slot="popover-trigger" {...props} />;
}

function PopoverContent({
  className,
  align = "start",
  sideOffset = 6,
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Content>) {
  return (
    <PopoverPrimitive.Portal>
      <PopoverPrimitive.Content
        data-slot="popover-content"
        align={align}
        sideOffset={sideOffset}
        collisionPadding={12}
        className={cn(
          "z-50 flex w-[min(20rem,var(--radix-popover-content-available-width))] flex-col",
          "border border-rule bg-surface p-4 text-sm text-ink outline-hidden",
          "transition-opacity duration-100 data-closed:opacity-0 data-open:opacity-100",
          className,
        )}
        {...props}
      />
    </PopoverPrimitive.Portal>
  );
}

function PopoverAnchor({ ...props }: React.ComponentProps<typeof PopoverPrimitive.Anchor>) {
  return <PopoverPrimitive.Anchor data-slot="popover-anchor" {...props} />;
}

export { Popover, PopoverAnchor, PopoverContent, PopoverTrigger };
