"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-28 16:23:35.819483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_written', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('git_sha', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name='ck_ingestion_run_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_run_job_started', 'ingestion_run', ['job', 'started_at'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('licence', sa.Text(), nullable=True),
    sa.Column('licence_url', sa.Text(), nullable=True),
    sa.Column('licence_note', sa.Text(), nullable=True),
    sa.Column('default_verification', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.CheckConstraint("default_verification IN ('self_reported', 'register_confirmed', 'externally_audited', 'third_party_reported', 'unverified')", name='ck_source_default_verification'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disaster',
    sa.Column('glide_id', sa.Text(), nullable=False),
    sa.Column('reliefweb_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.PrimaryKeyConstraint('glide_id'),
    sa.UniqueConstraint('reliefweb_id', name='uq_disaster_reliefweb_id')
    )
    op.create_table('district',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('admin1_code', sa.Text(), nullable=False),
    sa.Column('admin1_name', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.CheckConstraint("code ~ '^NP[0-9]{4}$'", name='ck_district_code_format'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_district_admin1', 'district', ['admin1_code'], unique=False)
    op.create_table('organisations',
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('name_common', sa.Text(), nullable=False),
    sa.Column('org_type', sa.Text(), nullable=False),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('hq_city', sa.Text(), nullable=True),
    sa.Column('hq_source_url', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("org_type IN ('un_agency', 'red_cross_movement', 'ingo', 'national_ngo', 'community_org', 'diaspora_charity', 'foundation', 'government', 'platform', 'alliance', 'unknown')", name='ck_organisations_org_type'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index('ix_organisations_hq_country', 'organisations', ['hq_country'], unique=False)
    op.create_index('ix_organisations_org_type', 'organisations', ['org_type'], unique=False)
    op.create_table('district_alias',
    sa.Column('alias_norm', sa.Text(), nullable=False),
    sa.Column('district_code', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('acronym', 'local_script', 'former_name', 'misspelling', 'other')", name='ck_district_alias_kind'),
    sa.ForeignKeyConstraint(['district_code'], ['district.code'], ),
    sa.PrimaryKeyConstraint('alias_norm')
    )
    op.create_index('ix_district_alias_district', 'district_alias', ['district_code'], unique=False)
    op.create_table('org_alias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alias_norm', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('acronym', 'local_script', 'former_name', 'misspelling', 'other')", name='ck_org_alias_kind'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_norm', name='uq_org_alias_norm')
    )
    op.create_index('ix_org_alias_org', 'org_alias', ['org_id'], unique=False)
    op.create_table('org_datum',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('fiscal_year', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('verification', sa.Text(), nullable=False),
    sa.Column('gap_reason', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('is_gap', sa.Boolean(), sa.Computed('value IS NULL', persisted=True), nullable=False),
    sa.CheckConstraint("gap_reason IN ('not_searched', 'searched_not_found', 'source_unreachable', 'not_public')", name='ck_org_datum_gap_reason'),
    sa.CheckConstraint("scope IN ('global', 'nepal_only', 'unknown')", name='ck_org_datum_scope'),
    sa.CheckConstraint("value_type IN ('string', 'integer', 'number', 'boolean', 'money', 'date')", name='ck_org_datum_value_type'),
    sa.CheckConstraint("verification IN ('self_reported', 'register_confirmed', 'externally_audited', 'third_party_reported', 'unverified')", name='ck_org_datum_verification'),
    sa.CheckConstraint('(value IS NOT NULL AND source_url IS NOT NULL AND gap_reason IS NULL) OR (value IS NULL AND note IS NOT NULL AND gap_reason IS NOT NULL)', name='ck_org_datum_provenance'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_datum_gap', 'org_datum', ['is_gap'], unique=False)
    op.create_index('ix_org_datum_org', 'org_datum', ['org_id'], unique=False)
    op.create_index('uq_org_datum_current', 'org_datum', ['org_id', 'path'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_table('org_registration',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('registry', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.Column('verification', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('gap_reason', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("gap_reason IN ('not_searched', 'searched_not_found', 'source_unreachable', 'not_public')", name='ck_org_registration_gap_reason'),
    sa.CheckConstraint("registry IN ('NP_SWC', 'NP_DAO', 'NP_CDO', 'UK_CC', 'UK_OSCR', 'US_IRS', 'DE_VEREINSREGISTER', 'DE_DZI', 'DE_ITZ', 'CH_ZEWO', 'AT_OSGS', 'IATI', 'UN', 'OTHER')", name='ck_org_registration_registry'),
    sa.CheckConstraint("verification IN ('self_reported', 'register_confirmed', 'externally_audited', 'third_party_reported', 'unverified')", name='ck_org_registration_verification'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'registry', 'content_hash', name='uq_org_registration_content')
    )
    op.create_index('ix_org_registration_org', 'org_registration', ['org_id'], unique=False)
    op.create_table('org_warning',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("type IN ('regulator_inquiry', 'fraud_allegation', 'watchdog_alert', 'delisting', 'sanction', 'media_report', 'other')", name='ck_org_warning_type'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'content_hash', name='uq_org_warning_content')
    )
    op.create_table('report',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disaster_glide_id', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_sha256', sa.Text(), nullable=True),
    sa.Column('body_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_extraction_error', sa.Text(), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disaster_glide_id'], ['disaster.glide_id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_report_url')
    )
    op.create_index('ix_report_body_sha256', 'report', ['body_sha256'], unique=False)
    op.create_index('ix_report_disaster_published', 'report', ['disaster_glide_id', 'published_at'], unique=False)
    op.create_table('report_source',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'publisher')
    )
    op.create_table('response_statement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.Column('org_name_raw', sa.Text(), nullable=False),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('where_raw', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('happened_on', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_offset', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('verification', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('relief_distribution', 'search_and_rescue', 'medical', 'shelter', 'wash', 'cash_assistance', 'food', 'logistics', 'assessment', 'appeal_launched', 'funding_pledged', 'presence_declared', 'staff_deployed', 'needs_statement', 'other')", name='ck_response_statement_activity_type'),
    sa.CheckConstraint("array_length(regexp_split_to_array(btrim(quote), '\\s+'), 1) <= 40", name='ck_response_statement_quote_words'),
    sa.CheckConstraint("status IN ('auto', 'needs_review', 'approved', 'rejected_unverbatim')", name='ck_response_statement_status'),
    sa.CheckConstraint("verification IN ('self_reported', 'register_confirmed', 'externally_audited', 'third_party_reported', 'unverified')", name='ck_response_statement_verification'),
    sa.CheckConstraint('amount IS NULL OR currency IS NOT NULL', name='ck_response_statement_amount_currency'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.org_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'content_hash', name='uq_response_statement_content')
    )
    op.create_index('ix_response_statement_org', 'response_statement', ['org_id'], unique=False)
    op.create_index('ix_response_statement_report', 'response_statement', ['report_id'], unique=False)
    op.create_index('ix_response_statement_status', 'response_statement', ['status'], unique=False)
    op.create_table('statement_district',
    sa.Column('statement_id', sa.BigInteger(), nullable=False),
    sa.Column('district_code', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.CheckConstraint("resolution IN ('stated', 'inherited_from_report')", name='ck_statement_district_resolution'),
    sa.ForeignKeyConstraint(['district_code'], ['district.code'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['response_statement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statement_id', 'district_code')
    )
    op.create_index('ix_statement_district_district', 'statement_district', ['district_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_statement_district_district', table_name='statement_district')
    op.drop_table('statement_district')
    op.drop_index('ix_response_statement_status', table_name='response_statement')
    op.drop_index('ix_response_statement_report', table_name='response_statement')
    op.drop_index('ix_response_statement_org', table_name='response_statement')
    op.drop_table('response_statement')
    op.drop_table('report_source')
    op.drop_index('ix_report_disaster_published', table_name='report')
    op.drop_index('ix_report_body_sha256', table_name='report')
    op.drop_table('report')
    op.drop_table('org_warning')
    op.drop_index('ix_org_registration_org', table_name='org_registration')
    op.drop_table('org_registration')
    op.drop_index('uq_org_datum_current', table_name='org_datum', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_index('ix_org_datum_org', table_name='org_datum')
    op.drop_index('ix_org_datum_gap', table_name='org_datum')
    op.drop_table('org_datum')
    op.drop_index('ix_org_alias_org', table_name='org_alias')
    op.drop_table('org_alias')
    op.drop_index('ix_district_alias_district', table_name='district_alias')
    op.drop_table('district_alias')
    op.drop_index('ix_organisations_org_type', table_name='organisations')
    op.drop_index('ix_organisations_hq_country', table_name='organisations')
    op.drop_table('organisations')
    op.drop_index('ix_district_admin1', table_name='district')
    op.drop_table('district')
    op.drop_table('disaster')
    op.drop_table('source')
    op.drop_index('ix_ingestion_run_job_started', table_name='ingestion_run')
    op.drop_table('ingestion_run')
    # ### end Alembic commands ###
