"""amount basis on response statement

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-28 16:58:04.736515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_statement', sa.Column('amount_basis', sa.Text(), server_default=sa.text("'reported'"), nullable=False))
    op.create_check_constraint('ck_response_statement_amount_basis', 'response_statement', "amount_basis IN ('reported', 'appeal', 'pledged', 'raised', 'released', 'disbursed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_response_statement_amount_basis', 'response_statement', type_='check')
    op.drop_column('response_statement', 'amount_basis')
    # ### end Alembic commands ###
