"""queued runs and hand-researched statements

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-28 18:32:07.138417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerated part.
    op.alter_column('response_statement', 'quote',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_check_constraint('ck_response_statement_quote_required_for_extracted', 'response_statement', "quote IS NOT NULL OR model = 'hand_research'")

    # Hand-written. Alembic diffs whether a CHECK exists, not what its expression says, so a
    # changed expression is invisible to autogenerate and has to be dropped and recreated by hand.
    #
    # The 40-word rule now has to tolerate a NULL quote: array_length(...) of a NULL is NULL, the
    # CHECK evaluates to UNKNOWN and passes, but writing it explicitly is what makes the intent
    # readable to the next person rather than a happy accident of three-valued logic.
    op.drop_constraint('ck_response_statement_quote_words', 'response_statement', type_='check')
    op.create_check_constraint(
        'ck_response_statement_quote_words',
        'response_statement',
        r"quote IS NULL OR array_length(regexp_split_to_array(btrim(quote), '\s+'), 1) <= 40",
    )

    # "queued" joins the run statuses. The admin endpoint records a queued run and returns; the
    # pipeline service drains queued runs on its next tick. The API never runs a job in-process.
    op.drop_constraint('ck_ingestion_run_status', 'ingestion_run', type_='check')
    op.create_check_constraint(
        'ck_ingestion_run_status',
        'ingestion_run',
        "status IN ('queued', 'running', 'succeeded', 'failed')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # A queued run has no equivalent in the old vocabulary, and leaving one behind would fail the
    # narrower CHECK. Failing a run that never started is the honest reading: nothing ran.
    op.execute(
        "UPDATE ingestion_run SET status = 'failed',"
        " error = COALESCE(error, 'queued run discarded by migration downgrade')"
        " WHERE status = 'queued'"
    )
    op.drop_constraint('ck_ingestion_run_status', 'ingestion_run', type_='check')
    op.create_check_constraint(
        'ck_ingestion_run_status',
        'ingestion_run',
        "status IN ('running', 'succeeded', 'failed')",
    )

    op.drop_constraint('ck_response_statement_quote_words', 'response_statement', type_='check')
    op.create_check_constraint(
        'ck_response_statement_quote_words',
        'response_statement',
        r"array_length(regexp_split_to_array(btrim(quote), '\s+'), 1) <= 40",
    )

    # Hand-researched statements have no quote, so the column cannot go back to NOT NULL while any
    # of them exist. Dropping them is not this migration's call to make silently.
    op.execute("DELETE FROM response_statement WHERE quote IS NULL")
    op.drop_constraint('ck_response_statement_quote_required_for_extracted', 'response_statement', type_='check')
    op.alter_column('response_statement', 'quote',
               existing_type=sa.TEXT(),
               nullable=False)
