"""hand research statement identity

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-28 19:57:07.415400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_statement', sa.Column('activity_norm', sa.Text(), sa.Computed("lower(regexp_replace(btrim(activity), '\\s+', ' ', 'g'))", persisted=True), nullable=False))
    op.create_index('uq_response_statement_hand_research', 'response_statement', ['report_id', 'org_id', 'activity_norm'], unique=True, postgresql_where=sa.text("model = 'hand_research'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_response_statement_hand_research', table_name='response_statement', postgresql_where=sa.text("model = 'hand_research'"))
    op.drop_column('response_statement', 'activity_norm')
    # ### end Alembic commands ###
