"""donation channel on a datum

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-28 21:45:00.000000

Hand-written, not autogenerated. Alembic does not diff a CHECK expression, so the enum constraint
below would never appear in an autogenerate run - the same trap that made migration 0004
necessary, guarded by test_no_enum_check_has_drifted_from_the_models.

channel_type and flood_specific are sibling facts of a donation_channel datum, the way currency,
fiscal_year and scope are sibling facts of a money datum. Both are null on every other path, so
the columns are nullable and no backfill is needed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('org_datum', sa.Column('channel_type', sa.Text(), nullable=True))
    op.add_column('org_datum', sa.Column('flood_specific', sa.Boolean(), nullable=True))
    op.create_check_constraint(
        'ck_org_datum_channel_type',
        'org_datum',
        "channel_type IN ('donation_page', 'bank_transfer_page', 'platform_page')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_org_datum_channel_type', 'org_datum', type_='check')
    op.drop_column('org_datum', 'flood_specific')
    op.drop_column('org_datum', 'channel_type')
